# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_reglogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretcontent', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likers', models.ManyToManyField(related_name='secretlikers', to='app_reglogin.User')),
                ('secretuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretusers', to='app_reglogin.User')),
            ],
        ),
    ]
